import { Box, Flex } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import LandingImg from "../components/LandingImg";
import LandingText from "../components/LandingText";
import Navbar from "../components/layout/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex gap={"12em"} marginTop={"4em"} justifyContent={"center"}>
        <LandingText />
        <LandingImg />
      </Flex>
    </div>
  );
}
